package com.openfeign.doctor_service.controller;

import com.openfeign.doctor_service.dto.DoctorRequest;
import com.openfeign.doctor_service.model.Doctor;
import com.openfeign.doctor_service.service.DoctorService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * ================================================================
 * REST CONTROLLER — DoctorController
 * ================================================================
 * Exposes the HTTP API for the Doctor Service.
 * These are the EXACT endpoints that the Appointment Service
 * calls via Feign Client (DoctorClient.java).
 *
 * @RestController = @Controller + @ResponseBody
 * → All method return values are automatically serialized to JSON
 * and written to the HTTP response body.
 * → No need to annotate each method with @ResponseBody.
 * @RequestMapping("/api/doctors") → Base path for all endpoints in this controller.
 * Every @GetMapping, @PostMapping etc. below is relative to this.
 * @RequiredArgsConstructor (Lombok)
 * → Generates a constructor for all 'final' fields.
 * Spring uses this constructor to inject DoctorService.
 * Equivalent to writing @Autowired on a constructor manually.
 * ================================================================
 */

@Slf4j
@RestController
@RequestMapping("/api/doctors")
@RequiredArgsConstructor
public class DoctorController {

    // Spring injects DoctorService via the constructor generated by @RequiredArgsConstructor
    private final DoctorService doctorService;

    /**
     * GET /api/doctors
     * Returns all doctors in the system.
     * <p>
     * ResponseEntity<List<Doctor>> lets us control:
     * - The HTTP status code (200 OK)
     * - Response headers (if needed)
     * - The body (the list of doctors)
     * <p>
     * ResponseEntity.ok(body) is a shortcut for:
     * ResponseEntity.status(200).body(body)
     */

    @GetMapping
    public ResponseEntity<List<Doctor>> getAllDoctors() {
        log.info("Received request: GET /api/doctors");
        return ResponseEntity.ok(doctorService.findAll());
    }

    /**
     * GET /api/doctors/{id}
     * Returns a single doctor by ID.
     * <p>
     * FEIGN CONNECTION: DoctorClient.getDoctorById(Long id) calls this endpoint.
     * When appointment-service calls doctorClient.getDoctorById(1L),
     * the HTTP request arrives here with id=1 in the path.
     *
     * @PathVariable Long id → Spring extracts the {id} from the URL path
     * and converts it to a Long automatically.
     * <p>
     * Optional.map(ResponseEntity::ok) → if doctor exists, wrap in 200 OK
     * .orElse(ResponseEntity.notFound().build()) → if not, return 404
     */


    @GetMapping("/{id}")
    public ResponseEntity<Doctor> getDoctorById(@PathVariable Long id) {
        log.info("GET /api/doctors/{}", id);
        return doctorService.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * GET /api/doctors/available
     * Returns only doctors with available=true.
     * <p>
     * FEIGN CONNECTION: DoctorClient.getAvailableDoctors() calls this.
     * Try stopping this service and calling the appointment-service's
     * /api/appointments/doctors/available — you'll see the circuit breaker
     * open and DoctorClientFallback return an empty list instead.
     */

    @GetMapping("/available")
    public ResponseEntity<List<Doctor>> getAvailableDoctors() {
        log.info("Received request: GET /api/doctors/available");
        return ResponseEntity.ok(doctorService.findAvailable());
    }

    /**
     * GET /api/doctors/specialization/{specialization}
     * Returns doctors matching the given specialization (case-insensitive).
     * Example: GET /api/doctors/specialization/Cardiologist
     */

    @GetMapping("/specialization/{specialization}")
    public ResponseEntity<List<Doctor>> getBySpecialization(@PathVariable String specialization) {
        log.info("Received request: GET /api/doctors/specialization/{}", specialization);
        return ResponseEntity.ok(doctorService.findBySpecialization(specialization));
    }

    /**
     * POST /api/doctors
     * Creates a new doctor.
     *
     * @Valid triggers the validation annotations on DoctorRequest
     * (@NotBlank, @Email etc.). If validation fails, Spring returns
     * HTTP 400 Bad Request automatically — this method is never entered.
     * @RequestBody → Spring deserializes the JSON request body into DoctorRequest
     * using Jackson (Jackson is auto-configured by spring-boot-starter-web).
     * <p>
     * HttpStatus.CREATED = HTTP 201, which is the correct status for a
     * successful resource creation (not 200).
     */

    @PostMapping
    public ResponseEntity<Doctor> createDoctor(@Valid @RequestBody DoctorRequest request) {
        log.info("Received request: POST /api/doctors - {}", request.getName());
        Doctor created = doctorService.create(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    /**
     * PUT /api/doctors/{id}
     * Full update (replaces all fields) for a doctor.
     * Returns 200 with updated doctor, or 404 if doctor not found.
     */

    @PutMapping("/{id}")
    public ResponseEntity<Doctor> updateDoctor(@PathVariable Long id,
                                               @Valid @RequestBody DoctorRequest request) {
        log.info("Received request: PUT /api/doctors/{}", id);
        return doctorService.update(id, request)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * DELETE /api/doctors/{id}
     * Removes a doctor. Returns 204 No Content on success, 404 if not found.
     * ResponseEntity<Void> means the response body is empty (correct for DELETE).
     */

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteDoctor(@PathVariable Long id) {
        log.info("Received request: DELETE /api/doctors/{}", id);
        return doctorService.delete(id)
                ? ResponseEntity.noContent().build()
                : ResponseEntity.notFound().build();
    }


}
